name: Test

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        django-version: ["2.2", "3.2", "4.0"]
        grappelli: ["0", "1"]
        exclude:
          - django-version: "4.0"
            grappelli: "1"
          - python-version: "3.7"
            django-version: "4.0"
          - python-version: "3.10"
            django-version: "2.2"
        include:
          - grappelli: "0"
            name-suffix: ""
          - grappelli: "1"
            name-suffix: " + grappelli"

    runs-on: ubuntu-latest
    name: Django ${{ matrix.django-version }} (Python ${{ matrix.python-version }})${{ matrix.name-suffix }}

    env:
      DJANGO: ${{ matrix.django-version }}
      GRAPPELLI: ${{ matrix.grappelli }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Setup chromedriver
      uses: nanasess/setup-chromedriver@v1.0.5

    - name: Install tox
      run: |
       python3 -m pip install tox tox-gh-actions

    - name: Run tests
      run: |
        tox -- --selenium=chrome-headless --verbosity=3 --failfast || \
        tox -- --selenium=chrome-headless --verbosity=3 --failfast || \
        tox -- --selenium=chrome-headless --verbosity=3

  success:
    needs: build
    runs-on: ubuntu-latest
    name: Test Successful
    steps:
      - name: Success
        run: echo Test Successful
